name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 33306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        wget --tries 10 --waitretry 10 --retry-connrefused 127.0.0.1:33306
        mysql -h 127.0.0.1 -P 33306 -uroot -p'password' -e "ALTER USER root@'%' IDENTIFIED WITH mysql_native_password BY 'password'"
        bundle exec rake
